In [2]:
import pprint
import random
from collections import Counter
import pandas as pd

In [44]:

# matki_DB 경로설정
tmp_df = pd.read_csv("./matki_DB.csv")
region_lst = list(set(tmp_df["region"].to_list()))
print(region_lst)
print("깐깐한 리뷰어들이 극찬한 음식점을 찾아줍니다.")


cat = [
    "베이커리,카페",
    "패스트푸드",
    "샌드위치,샐러드",
    "육류",
    "해산물",
    "한식",
    "일식",
    "양식",
    "중식",
    "기타",
    "면류",
    "술집",
    "찌개,국밥",
]

region = -2
restaurantAverageRating = 3
personalAverageScore = 4.3
thisRestaurantScore = 4
RestaurantType = '중식'

personalAverageScoreRow = 2.5
thisRestaurantScoreRow = 2.0
row_df = tmp_df[
    (tmp_df["rate"] >= personalAverageScoreRow)
    & (tmp_df["reviewAt"] <= thisRestaurantScoreRow)
]


result_df = tmp_df[
    (tmp_df["region"].isin([region_lst[region]]))
    & (tmp_df["score_min"] >= restaurantAverageRating)
    & (tmp_df["rate"] <= personalAverageScore)
    & (tmp_df["reviewAt"] >= thisRestaurantScore)
    & (tmp_df["cat1"] == RestaurantType)
]

# print(result_df[result_df['reviewer_id']=='맵핑'])
# tmp_df

['광흥창역', '영등포구청', '양재역', '가산디지털역', '판교역', '망원역', '신촌역', '속초', '강남역', '오리역', '합정역', '삼성역', '응암역']
깐깐한 리뷰어들이 극찬한 음식점을 찾아줍니다.

In [45]:
row_df

,region,name,addresse,cat1,cat2,review_num,blog_review_num,score_min,likePoint,likePointCnt,rate,reviewerCnt,reviewAt,review,reviews_date,reviewer_id
3,삼성역,팀호완 삼성점,서울 강남구 봉은사로86길 30 1층 (우)06165,중식,샤오마이 3pcs ->가격:6500 차슈 라이스 롤 3pcs ->가격:8000 사천...,17.0,824,3.5,맛@가성비@친절@분위기@,3@1@1@1@,2.7,89,1.0,"몽중헌까진 아니더라도 가격대에 맞는 분위기와 서비스를 기대했는데, 최악이네요.메뉴 ...",2022.09.30.,ESTJ
35,삼성역,팀호완 삼성점,서울 강남구 봉은사로86길 30 1층 (우)06165,중식,샤오마이 3pcs ->가격:6500 차슈 라이스 롤 3pcs ->가격:8000 사천...,17.0,824,3.5,맛@가성비@친절@분위기@,3@1@1@1@,2.7,19,1.0,홍콩 팀호완 생각하고 가면 실망할듯 합니다.굳이 비교하자면 딘타이펑이 조금 더 나은...,2022.04.24.,맵핑
37,삼성역,팀호완 삼성점,서울 강남구 봉은사로86길 30 1층 (우)06165,중식,샤오마이 3pcs ->가격:6500 차슈 라이스 롤 3pcs ->가격:8000 사천...,17.0,824,3.5,맛@가성비@친절@분위기@,3@1@1@1@,4.0,4,1.0,맛은 있었지만 가격대비 만족도는 떨어졌고 무엇보다도 카운터의 남자 직원분이 손님에게...,2022.04.10.,ㅈㅇ
44,삼성역,팀호완 삼성점,서울 강남구 봉은사로86길 30 1층 (우)06165,중식,샤오마이 3pcs ->가격:6500 차슈 라이스 롤 3pcs ->가격:8000 사천...,17.0,824,3.5,맛@가성비@친절@분위기@,3@1@1@1@,3.6,49,1.0,"대실망 금액은 20% 에서 25 % 올리고 음식 사이즈는 엄청 줄이고, 장난하냐?...",2022.03.03.,Bloody hot
49,삼성역,팀호완 삼성점,서울 강남구 봉은사로86길 30 1층 (우)06165,중식,샤오마이 3pcs ->가격:6500 차슈 라이스 롤 3pcs ->가격:8000 사천...,17.0,824,3.5,맛@가성비@친절@분위기@,3@1@1@1@,3.1,29,1.0,PC방에서 시켜먹는 중국음식 느낌,2022.02.03.,MrH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102095,신촌역,동강참치,서울 서대문구 연세로2길 83 (우)03778,일식,"['참치특회(1인)\n35,000', '스페셜(1인)\n50,000', '골드(1인...",NaN,7,4.2,맛@가성비@친절@,2@1@1@,3.8,5,1.0,갔는데 불도 켜져있는데 장사를 안하시네요? 오라고하시다가 다시전화와서 영업안한다고가...,2021.09.11.,~~
102097,신촌역,초당쌈밥 신촌본점,서울 서대문구 연세로12길 37-4 (우)03776,쌈밥,"['우렁된장쌈밥\n8,000', '우렁맑은된장쌈밥\n8,000', '불고기쌈밥\n9...",1.0,2,3.2,맛@가성비@,1@1@,3.0,5,2.0,한 눈에 봐도 시들시들해 보이는 쌈채소를 내 주셨습니다. 엥간하면 참고 먹으려고 했...,2022.07.16.,비비빅
102098,신촌역,초당쌈밥 신촌본점,서울 서대문구 연세로12길 37-4 (우)03776,쌈밥,"['우렁된장쌈밥\n8,000', '우렁맑은된장쌈밥\n8,000', '불고기쌈밥\n9...",1.0,2,3.2,맛@가성비@,1@1@,2.6,11,1.0,웬만해선 내가 쌈밥집 좋게 보는데 여긴 최악.쌈채소가 오래되어서 검고 어떤 건 해초...,2020.08.25.,예비
102102,신촌역,초당쌈밥 신촌본점,서울 서대문구 연세로12길 37-4 (우)03776,쌈밥,"['우렁된장쌈밥\n8,000', '우렁맑은된장쌈밥\n8,000', '불고기쌈밥\n9...",1.0,2,3.2,맛@가성비@,1@1@,3.5,21,1.0,NaN,2020.05.05.,pandemico
102105,신촌역,초당쌈밥 신촌본점,서울 서대문구 연세로12길 37-4 (우)03776,쌈밥,"['우렁된장쌈밥\n8,000', '우렁맑은된장쌈밥\n8,000', '불고기쌈밥\n9...",1.0,2,3.2,맛@가성비@,1@1@,3.0,13,2.0,쌈이 신선하지 않았음.... 쌈장이나 다른 음식 맛은 괜찮았지만.... 쌈이 너무너...,2019.11.19.,먹

In [15]:

print()
print("-" * 80)
print(RestaurantType, "(음식점, 깐깐한 리뷰어 수)")
print("-" * 80)
result_lst = Counter(result_df["name"].to_list()).most_common()
for result in result_lst:

    print("-" * 80)
    print(result)
    personalAverageScoreRow = 3.2
    thisRestaurantScore = 2.0
    print(result_df.columns)
    tmp_df = result_df[
        (result_df["name"] == result[0])
        & (tmp_df["rate"] >= personalAverageScoreRow)
        & (tmp_df["reviewAt"] <= thisRestaurantScore)
    ]
    print(tmp_df)
    if len(tmp_df) >= 1:
        print("불호가 너무 많은 식당입니다.")
        continue
    else:
        print('불호아님')
    
    # detail = result_df[result_df["name"] == result[0]].iloc[0, :]
    # if type(detail["likePoint"]) != float:
    #     likePoint = detail["likePoint"].split("@")
    #     likePointCnt = detail["likePointCnt"].split("@")
    #     likePointList = []
    #     for l, c in zip(likePoint, likePointCnt):
    #         tmp = l + ": " + c
    #         likePointList.append(tmp)
    #         likePoint_tmp = "/ ".join(likePointList)

    #     print(likePoint_tmp)
    # print()
    # print(detail["cat2"])

--------------------------------------------------------------------------------
한식 (음식점, 깐깐한 리뷰어 수)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
('승남집', 39)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('소문난식당', 29)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('개성손만두', 22)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('당산빨간주꾸미', 12)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('부뚜막청국장 영등포점', 9)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('소정담', 3)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('우동가게', 3)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('동대문엽기떡볶이 영등포구청점', 3)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('명동식당', 3)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('명가생선구이', 3)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('미락소바', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('차호로록', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('까치네김밥', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('박찬숙순대국', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('황해도구월산', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('손큰할매순대국 영등포구청점', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('선비네', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('왕대박김밥', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('바삭하게', 2)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('구석집', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('한성삼계탕', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('희락돈까스', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('까치네분식', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('본래순대 영등포구청점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('강릉수산 영등포구청점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('본죽 영등포구청점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('육갑식당 당산점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('송화잔기지떡 영등포점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('시골쌈밥', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('진미식당', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('궁중삼계탕', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('태리로제떡볶이 영등포점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('어리랑 영등포구청점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('미락카츠 본점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('한솥도시락 당산동4가점', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('호박집', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',
       'reviewerCnt', 'reviewAt', 'review', 'reviews_date', 'reviewer_id'],
      dtype='object')
Empty DataFrame
Columns: [region, name, addresse, cat1, cat2, review_num, blog_review_num, score_min, likePoint, likePointCnt, rate, reviewerCnt, reviewAt, review, reviews_date, reviewer_id]
Index: []
불호아님
--------------------------------------------------------------------------------
('온포식당', 1)
Index(['region', 'name', 'addresse', 'cat1', 'cat2', 'review_num',
       'blog_review_num', 'score_min', 'likePoint', 'likePointCnt', 'rate',

In [ ]:
print("-" * 80)
choicelist = random.choice(list(result_lst))
print("랜덤 픽 : ", choicelist)
print("-" * 80)

In [ ]:
        detail = result_df[result_df["name"] == result[0]].iloc[0, :]
        if type(detail["likePoint"]) != float:
            likePoint = detail["likePoint"].split("@")
            likePointCnt = detail["likePointCnt"].split("@")
            likePointList = []
            for l, c in zip(likePoint, likePointCnt):
                tmp = l + ": " + c
                likePointList.append(tmp)
                likePoint_tmp = "/ ".join(likePointList)

            print(likePoint_tmp)
        print()
        print(detail["cat2"])

    except Exception as err:
        print(err)
        continue
print("-" * 80)
choicelist = random.choice(list(result_lst))
print("랜덤 픽 : ", choicelist)
print("-" * 80)